version: "3"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: simulator
    volumes:
      - .:/go/src/
    extra_hosts: #Server para conectar as aplicações que estão em diferentes redes
      - "host.docker.internal:172.17.0.1"
